### ISSUE TITLE
Wrong link for TG chat

### ISSUE THREAD

**Issue by nicl-nno** [aimclub/Fedot.Industrial#127]
This ![image](https://github.com/aimclub/Fedot.Industrial/assets/5711814/4cd1ce97-cb9a-4df4-8f0c-7a5f1c047dd4)

Should be: https://t.me/FEDOT_helpdesk instead of 

![image](https://github.com/aimclub/Fedot.Industrial/assets/5711814/870f3365-e6c6-48fc-8063-56642e5f3274)

**Comment by technocreep** [comment]
fixed in this #128 PR, [this commit](https://github.com/aimclub/Fedot.Industrial/pull/128/commits/ffbb7eb40b4202445b2f67d974d69019289ade14)
