### ISSUE TITLE
Implement time series forecasting 

### ISSUE THREAD

**Issue by nicl-nno** [aimclub/Fedot.Industrial#56]
TSF functionality should be implemented using FEDOT as a core.

The DL models for forecasting should be added as candidate operations.

They can be obtained from:
https://github.com/jdb78/pytorch-forecasting

**Comment by v1docq** [comment]
Касательно группировки компонент. Есть "простой" и "сложный" вариант.
Простой вариант - Группировка на основе матрицы взаимных корреляций. Выглядит она так.
![image](https://github.com/aimclub/Fedot.Industrial/assets/48867680/cb13c224-b702-41c9-910b-084465e75c80)
Это матрица размером KxK, где k - число компонент. Каждый элемент матрица - метрика близости собственных векторов. Сам алгоритм:
![image](https://github.com/aimclub/Fedot.Industrial/assets/48867680/2a3552a1-b479-4c01-935f-b14b8e5c0c40)
Функции для реализации алгоритма лежат [здесь](fedot_ind/core/operation/transformation/data/eigen.py)
Вариант посложнее - группировка на основе частного анализа и анализа регулярности угла между собственными векторами. [Статья](https://arxiv.org/pdf/2302.08993.pdf). Мини разбор отправил ввиде пдф файла.

**Comment by v1docq** [comment]
Касательно группировки компонент матрицы V.
Вижу здесь два подхода. Первый это мы проводим анализ компонент матрицы U (матрицы в которой вектора это "типовые" временные подпоследовательности). Тут идея в том что мы группируем между собой "типовые" временные подпоследовательности (тренды, колебания и прочее). Допустим мы знаем что вектора Un и Un+1 коррелируют между собой, тогда мы домножаем каждый из них на соотвестующие им собственные числа, складываем получившиеся вектора и потом каким то образом "усредняем". Таким образом у нас получится набор из типовых "трендов", "циклик" и прочего. Возникает вопрос - а какие тогда брать вектора Vn (вектора которые описывают временную динамику каждой из типовых компонент)? Первая стратегия - брать вектор Vn, который соотвествует наибольшему собственному значению вектора Un из которого был получен соотвествующий "типовой" вектор. Вторая стратегия - "усреднять" динамики (брать взвешенную комбинацию или использовать "более слабые" динамикак как экзогенные переменные)
![image](https://github.com/aimclub/Fedot.Industrial/assets/48867680/8f20da28-81cd-4e7d-9b7b-1ddcab747d4b)

**Comment by valer1435** [comment]
Добавил модель, использующую ансамбль предсказаний моделей autoTheta, autoETS, autoARIMA для предсказания динамик VT

**Comment by v1docq** [comment]
https://giotto-ai.github.io/gtda-docs/0.5.1/notebooks/time_series_forecasting.html

В этом блокноте показано, как с помощью giotto-tda можно создавать топологические признаки для задач прогнозирования временных рядов. Топологические признаки создаются на основе последовательных скользящих окон по данным. В моделях скользящих окон единый массив временных рядов X формы (n_timestamps, n_features) превращается во временной ряд окон по данным, имеющий новую форму (n_windows, n_samples_per_window, n_features). При построении моделей прогнозирования со скользящими окнами возникают две основные проблемы.

Целевая переменная должна быть правильно "выровнена" с каждым окном, чтобы задача прогнозирования была осмысленной и, например, не происходила "утечка" информации из будущего. В частности, необходимо "передискретизировать" y так, чтобы она тоже имела длину n_окон.

Для решения этих проблем предоставляет набор трансформаторов с методами resample, transform_resample и fit_transform_resample.
