### ISSUE TITLE
add CUR decompostion for big (>100x100) Hankel matrices

### ISSUE THREAD

**Issue by v1docq** [aimclub/Fedot.Industrial#74]
**Проблема** Для очень больших матриц считать свд довольно затратно, можно воспользоваться методом randomized_svd, но тогда не совсем ясно как бороться с стохастичностью при получении собственных векторов (а это важно в нашей задаче). Данную проблем можно решить с помощь CUR разложения.

**Идея** Исходная матрица X = L* + S*, где L - малоранговая разреженная составляющая, S - шумовая разреженная компонента. Тогда вместо SVD подхода в котором у нас X = UEV*, где столбцами  матриц U и V являются собственные вектора, мы можем записать X = CUR, где **столбцы матрицы С - это столбцы матрицы X**, **а строки матрицы R - это строки матрицы X**. Понятно что размеры матриц С и R кратной меньше размеров исходной X. Сами строки/столбцы выбираются с помощью алгоритма семплирования и оценки ранга. Матрица U состоит из значений полученных на пересечении соотвествующих строк и столбцов (общие коээфициенты по сути). Т.Е. таким образом при даннном разложении мы не выполняем "преобразование координат", а работаем сразу в исходном пространстве и ищем такое преобразование (по сути линейный оператор) из пространства "столбцов" в пространство "строк", с условием чтоб ранг С и R = X.
Плюсы подхода:
Базис - исходные данные (временные подпоследовательности). Базис - разреженный. 
Минусы:
В базисе могут быть дупликанты (колонки с большой нормой или циклические компоненты).

Основная разница:
![image](https://github.com/aimclub/Fedot.Industrial/assets/48867680/66480567-672f-4088-95b4-28d744f7ce00)
Тензорная визуализация:
![image](https://github.com/aimclub/Fedot.Industrial/assets/48867680/b3967320-b128-4788-8d00-f6df9e412135)

**Задача:**
Реализовать этот метод разложения в data-driven basis, и использовать его при работе с большими матрицами.
**Ссылки:**
[Пример реализации алгоритма](https://github.com/shappiron/CUR_decomposition)
[Видео с пояснением](https://www.youtube.com/watch?v=WgK_D6IyDbM&list=PLLssT5z_DsK9JDLcT8T62VtzwyW9LNepV&index=52)
[Актуальная статья про тензорную реализацию этого подхода](https://arxiv.org/pdf/2305.04080.pdf)

**Comment by technocreep** [comment]
написал алгоритм, который требуется, согласно приведённым материалам:

```python
from typing import Tuple

import numpy as np


class CURDecomposition:
    def __init__(self, rank):
        self.rank = rank

    def fit_transform(self, matrix: np.ndarray) -> tuple:
        array = np.array(matrix.copy())
        c, w, r = self.select_rows_cols(array)
        u = np.linalg.pinv(w)
        return c, u, r

    def select_rows_cols(self, matrix: np.ndarray) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        col_norms = np.sum(matrix ** 2, axis=0)
        row_norms = np.sum(matrix ** 2, axis=1)

        # Compute the probabilities for selecting columns and rows
        p = col_norms / np.sum(col_norms)
        q = row_norms / np.sum(row_norms)

        # Select k columns and rows based on the probabilities p and q
        selected_cols = np.random.choice(matrix.shape[1], size=self.rank, replace=False, p=p)
        selected_rows = np.random.choice(matrix.shape[0], size=self.rank, replace=False, p=q)

        row_scale_factors = 1 / np.sqrt(self.rank * q[selected_rows])
        col_scale_factors = 1 / np.sqrt(self.rank * p[selected_cols])

        C_matrix = matrix[:, selected_cols] * col_scale_factors
        R_matrix = matrix[selected_rows, :] * row_scale_factors[:, np.newaxis]
        W_matrix = matrix[selected_rows, :][:, selected_cols]
        return C_matrix, W_matrix, R_matrix


if __name__ == '__main__':
    rank_ = 100
    cur = CURDecomposition(rank=rank_)
    arr = np.array([[1, 1, 1, 0, 0],
                    [3, 3, 3, 0, 0],
                    [4, 4, 4, 0, 0],
                    [5, 5, 5, 0, 0],
                    [0, 0, 0, 4, 4],
                    [0, 0, 0, 5, 5],
                    [0, 0, 0, 2, 2]])

    C, U, R = cur.fit_transform(arr)
    arr_approx = C @ U @ R

    L, S, R = np.linalg.svd(arr)
    arr_svd_approx = L[:, :rank_] @ np.diag(S[:rank_]) @ R[:rank_, :]

    svd_error = np.linalg.norm(arr - arr_svd_approx)
    cur_error = np.linalg.norm(arr - arr_approx)

```

[Пример реализации](https://github.com/shappiron/CUR_decomposition) алгоритма мне кажется не совсем рациональным, поскольку подразумевает выполнение SVD дважды на исходной матрице, хотя и работает куда лучше, чем мой вариант

В этой связи вопрос: что в моём случае происходит неверно?
