### ISSUE TITLE
architecture refactoring

### ISSUE THREAD

**Issue by v1docq** [aimclub/Fedot.Industrial#80]
Требуется либо избавиться от "ненужных модулей" либо объединить их между собой.
1. fedot_ind/core/operation/interfaces/industrial_preprocessing_strategy.py имеет вот такой словарь моделей из индастриала 
![image](https://github.com/aimclub/Fedot.Industrial/assets/48867680/d6b1cdc0-44be-4f68-9e93-ee319d2881de)
это позволяет совмещать оптимизатор федота и наши модели для настройки гиперпараметров и композирования. В то же время
существует fedot_ind/core/architecture/pipelines в котором есть решения по созданию "шаблонов/пресетов пайплайнов". Выглядит так:
![image](https://github.com/aimclub/Fedot.Industrial/assets/48867680/42f75b9a-3865-486e-b72c-4cbfe4fa5867) основная идея что операции там записаны в функциональном стиле с использованием монад/каррирования/композиции и всего прочего.
![image](https://github.com/aimclub/Fedot.Industrial/assets/48867680/b53a15fe-f7f1-4491-acec-24f0f0631783). Требуется решить следующие:
1. нужен ли этот модуль (например как удобная обертка для апи и составления пайплайнов в интерактивном режиме)
2. есть ли там операции которые нужно адаптировать под федот что использовать его оптимизатор
3. можно ли функциональную составляющую оттуда распространить на другие модули

**Comment by v1docq** [comment]
2. Заменить метод поиска пиков для массива коэфицентов полученныз после вейвлет преобразования
fedot_ind/core/models/signal/SignalExtractor.py здесь находиться модель для генерации признаков после вейвлет преобразования. У нее есть вот такой метод.

![image](https://github.com/aimclub/Fedot.Industrial/assets/48867680/e8afeb06-ab26-44ce-ae5e-838b74699a3c)
она подсчитывает число "пиков" (значения коээфициентов которые значимо отличаются от других), в зависимости от ряда гиперпараметров (расстояние между пиками, продолжительность пика, проч)

однако в scipy уже реализовано подобное. from scipy.signal import find_peaks_cwt
![image](https://github.com/aimclub/Fedot.Industrial/assets/48867680/d6a2c75e-a57e-4a02-a6fa-961d6e255c37)

параметры плюс минус все теже, разве что можно прокинуть свой тип вейвлета.

Выглядит как кандидат на рефакторинг.

**Comment by v1docq** [comment]
3. Использования методов поиска "оптимального окна" для определения начальных приблежений окон при ганкелизации матриц/ SSA прогнозе/ поиске сезонности.

вот здесь fedot_ind/core/operation/transformation/WindowSelection.py лежит класс в котором реализованы 4 метода для определения окна временного ряда. Окно дает представления о возможносй сезонности, о лучшем вложении для траекторной матрицы (что дает лучшую разделимость ряда и лучший базис). метод для получения лучшего окна  def get_window_size().
В самом коде много косяков:
1. (например фурье разложение написанно ручками, а не через scipy.signal)
![image](https://github.com/aimclub/Fedot.Industrial/assets/48867680/6a798341-f288-4da7-8141-617fdce7942f)
2. Очень большие куски кода с логическими ветвлениями внутри одной функции
![image](https://github.com/aimclub/Fedot.Industrial/assets/48867680/888f8ad1-0af1-4056-9f22-4a36d25b7cda)
3.Все методы открыты для вызова из класса хотя дальше этого класса нигде не используются

Что надо сделать.
1. Прикрутить этот класса к API индстриала чтоб этот класс реализовывал подбор начального приблежения "окна" для задач классификации  (если используетися data-driven basis) и задач прогнозирования с помощью SSA (для подбор окна траекторной матрицы, которая отражает цикличность временного ряда).
2. Реализовать пример для классификации и прогнозирования где окно подбирается с помощью этого метода и подбирается "рандомно" с каким то шагом. Сделать 2 примера для классификации и 2 для прогнозирования.

**Comment by v1docq** [comment]
4. Переработка топологического генератора признаков
4.1. вот эти 2 метода 
![image](https://github.com/aimclub/Fedot.Industrial/assets/48867680/9284adc3-4c2b-4fbd-8573-cebe4ed8521b)
и
![image](https://github.com/aimclub/Fedot.Industrial/assets/48867680/06e1846f-4011-406d-abbc-d6b32af73a0f)
могут быть переписаны в 1 с помощью fedot_ind/core/operation/transformation/data/hankel.py
![image](https://github.com/aimclub/Fedot.Industrial/assets/48867680/e879f663-cab0-4caa-8031-f1043872020c)

**Comment by v1docq** [comment]
По задаче 4.1 (переработка топологического генератора признаков)
1. Переписан метод generate_topological_features. 
![image](https://github.com/aimclub/Fedot.Industrial/assets/48867680/4942e8d7-9179-4b18-88ef-e921d1da9e08)
теперь внутри есть логическое ветвление для работы с многомерными рядами (несколько компонент базиса, несколько фурье гармоник) и для работы с одномерным рядом.
2. Переписан метод _generate_features_from_ts
![image](https://github.com/aimclub/Fedot.Industrial/assets/48867680/cdb26811-8a37-4444-a9b9-cd6725689c13)
теперь он состоит из 3 шагов. 1. Задание класса топологического трансфомера. 2. Формирование облака точек из временного ряда 3. Извлечение топологических признаков из облака точек
 3. Переписан метод  def __evaluate_persistence_params(self, ts_data):
![image](https://github.com/aimclub/Fedot.Industrial/assets/48867680/749295b4-0249-4786-bb4f-5e0b94318cf8)
это подстраховка на случай если не заданы параметры для формирования облака точек из временного ряда.
4. Добавлен пример запуска в докстринги класса
![image](https://github.com/aimclub/Fedot.Industrial/assets/48867680/892080ec-9852-486e-835f-9078a171f2a0)
5.переписан класс TopologicalTransformation fedot_ind/core/operation/transformation/data/point_cloud.py
![image](https://github.com/aimclub/Fedot.Industrial/assets/48867680/73abd08b-f4de-4dfe-858d-64851351ea53)
теперь для перевода в облако точек используется реализация HankelMatrix

**Comment by technocreep** [comment]
По алгоритмам подбора окна:

Переписан код класса [WindowSizeSelector](https://github.com/aimclub/Fedot.Industrial/blob/main/fedot_ind/core/operation/transformation/WindowSelection.py):

- оставил два метода – на основе Фурье преобразования (**DFT**) и автокорреляции (**AC**)
- из 300 строк осталось примерно 100 
- оба метода стали работать быстрее, благодаря использованию библиотек `scipy` и `statsmodels` (примерно 0.005 сек на временной ряд)
- добавлен метод для обработки датафрейма временных рядов

По поводу эффективности работы алгоритмов:
Если кратко, то в случае наличия выраженной циклической компоненты она непременно будет найдена, причём не важно, каким методом. Ниже на картинке приведён пример работы этих методов для временного ряда, полученного склеиванием нескольких сэмплов из датасета [Beef](http://www.timeseriesclassification.com/description.php?Dataset=Beef). Как видно, оба алгоритма показали идентичную длину окна, соответствующую длине одного сэмпла (они показаны разными цветами)

<img width="835" alt="Снимок экрана 2023-09-15 в 10 24 49" src="https://github.com/aimclub/Fedot.Industrial/assets/44948116/5ed3bed7-c047-4d26-b3af-14d7cd44a23b">

Однако, зачастую в задачах классификации циклика – понятие весьма условное. Например, в случае [EC200](http://www.timeseriesclassification.com/description.php?Dataset=ECG200), где каждый ряд - это фактически единичный удар сердца. В таком случае для целого набора ВР будет получено несколько вариантов окон, где была хоть какая-то корреляция. Тут встаёт вопрос в усреднении между предлагаемыми вариантами:

`np.mean`:
<img width="902" alt="Снимок экрана 2023-09-18 в 12 56 02" src="https://github.com/aimclub/Fedot.Industrial/assets/44948116/275e8352-bb9e-49d8-a2b4-2eb1ce683586">


или `np.median`:
<img width="904" alt="Снимок экрана 2023-09-18 в 12 55 57" src="https://github.com/aimclub/Fedot.Industrial/assets/44948116/e3437b7e-7de5-4691-a735-5c9d7956813f">


Кроме того, стоит отметить одну важную вещь, связанную с тем, как работает `AC метод`. Вот его код: 

```python
    def autocorrelation(self, time_series):
        acf_values = acf(time_series, fft=True, nlags=int(time_series.shape[0] / 2))

        peaks, _ = find_peaks(acf_values)
        peaks = peaks[np.logical_and(peaks >= self.window_min, peaks < self.window_max)]
        corrs = acf_values[peaks]

        if peaks.shape[0] == 0: # if there is no peaks in range (window_min, window_max) return window_min
            return self.window_range[0]
        return peaks[np.argmax(corrs)]
```

То есть среди коэффициентов автокорреляции ищутся пики, Х-координата которых соответствует длина окна. И эта кривая может выглядеть вот так:

- Удачный случай, есть пики и, значит, есть окна:
<img width="603" alt="Снимок экрана 2023-09-18 в 13 16 24" src="https://github.com/aimclub/Fedot.Industrial/assets/44948116/e71c0d64-3b40-401a-819e-ef9e0a98d690">

- Неудачный случай:
<img width="624" alt="Снимок экрана 2023-09-18 в 13 15 25" src="https://github.com/aimclub/Fedot.Industrial/assets/44948116/57b3927a-54d4-4278-8ce8-e8cd42f9ec71">

Поэтому более надёжным мне кажется метод DFT. Однако, важно ещё раз отметить, что эти методики призваны искать циклики в рядах. Поэтому, если в ряду не предполагается по логике какой-то циклический процесс, то полученное значение, например, 45 будет лишь говорить о том, что при такой величине окна наибольшая корреляция временного ряда с самим собой или какой-то синусоидой, но это может быть корреляция = 0.01
