### ISSUE TITLE
Not user-friendly examples

### ISSUE THREAD

**Issue by valer1435** [aimclub/Fedot.Industrial#92]
Unfortunately some examples are not user-friendly because they don't have any examples how to load data, for example. Also structure of examples should be refactored

**Comment by valer1435** [comment]
1) Почему-то ts_regression лежит в ts_forecasting https://github.com/aimclub/Fedot.Industrial/tree/main/examples/api_example/time_series/ts_forecasting
2) В этом же примере загружаются данные датасета, который есть в базе. Сомневаюсь, что кому-то кроме нас интересно  запускать пример на данных из базы. Нужно добавить пример загрузки своих данных из локального файла
![image](https://github.com/aimclub/Fedot.Industrial/assets/32017472/0553c94f-0c80-49d6-baf9-69fd9739acc1)
3) Там же вперемешку ноутбуки с py файлами. Думаю ноутбуки стоит перенести в отдельную папку (или хранить в папке версию ноутбука и py файла)
4) Ноутбук https://github.com/aimclub/Fedot.Industrial/blob/main/examples/api_example/ensembling/rank_ensemle.ipynb не содержит описаний
5) https://github.com/aimclub/Fedot.Industrial/blob/main/examples/api_example/computer_vision/object_detection/object_detection_example.ipynb нужен ли тут ямл конфиг? btw лог обучения в примерах можно убрать
6) https://github.com/aimclub/Fedot.Industrial/tree/main/examples/fedot этот пример не особо актуален, как мне кажется. Все это скрыто в api
7) https://github.com/aimclub/Fedot.Industrial/tree/main/examples/industrial_examples - нужен ли непонятный пример с ящиком в примерах? 
8) Тут что-то все перемешалось https://github.com/aimclub/Fedot.Industrial/blob/main/examples/pipeline_example/time_series/ts_regression/multi_ts_example.py
9) Общий момент по всем примерам - кмк лучше относительные пути не использовать, а использовать PROJECT_PATH
10) Общий момент по всем примерам - нужны примеры загрузки своих рядов в индастриал

**Comment by valer1435** [comment]
Ну и стоит проверить актуальность примеров, если этого не было перед релизом)

**Comment by v1docq** [comment]
> 1. Почему-то ts_regression лежит в ts_forecasting https://github.com/aimclub/Fedot.Industrial/tree/main/examples/api_example/time_series/ts_forecasting
> 2. В этом же примере загружаются данные датасета, который есть в базе. Сомневаюсь, что кому-то кроме нас интересно  запускать пример на данных из базы. Нужно добавить пример загрузки своих данных из локального файла
>    ![image](https://user-images.githubusercontent.com/32017472/271916789-0553c94f-0c80-49d6-baf9-69fd9739acc1.png)
> 3. Там же вперемешку ноутбуки с py файлами. Думаю ноутбуки стоит перенести в отдельную папку (или хранить в папке версию ноутбука и py файла)
> 4. Ноутбук https://github.com/aimclub/Fedot.Industrial/blob/main/examples/api_example/ensembling/rank_ensemle.ipynb не содержит описаний
> 5. https://github.com/aimclub/Fedot.Industrial/blob/main/examples/api_example/computer_vision/object_detection/object_detection_example.ipynb нужен ли тут ямл конфиг? btw лог обучения в примерах можно убрать
> 6. https://github.com/aimclub/Fedot.Industrial/tree/main/examples/fedot этот пример не особо актуален, как мне кажется. Все это скрыто в api
> 7. https://github.com/aimclub/Fedot.Industrial/tree/main/examples/industrial_examples - нужен ли непонятный пример с ящиком в примерах?
> 8. Тут что-то все перемешалось https://github.com/aimclub/Fedot.Industrial/blob/main/examples/pipeline_example/time_series/ts_regression/multi_ts_example.py
> 9. Общий момент по всем примерам - кмк лучше относительные пути не использовать, а использовать PROJECT_PATH
> 10. Общий момент по всем примерам - нужны примеры загрузки своих рядов в индастриал

1. Переместил
2. Добавил пример загрузки данных из локального файла
3. Ноутбуки тогда в отдельную папку вынес
4. Убрал
5. оставил пока что так
6. переработал пример
7. ящик убрал
8. переработал
9. поменял на PROJECT_PATH
10. поменял в рамках 2 пункта
